#resolver: lts-9.10
resolver: lts-10.4
packages:
- .
extra-deps:
- llvm-hs-pure-5.0.0
- llvm-hs-5.0.0
- megaparsec-6.2.0
- QuickCheck-2.10.1
flags:
  llvm-hs:
    shared-llvm: false
extra-package-dbs: []
